sparktw/urls.py
from django.conf.urls import url
from django.contrib import admin
from combat import views as combat_views
from auth import views as auth_views
from home import views as home_views
# from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^yeee/', admin.site.urls),
    url(r'^$', auth_views.home, name='home'),
    url(r'^challenges/$', combat_views.challenges, name='challenges'),
    url(r'^billboard/$', home_views.billboard, name='billboard'),
    url(r'^leaderboard/$', combat_views.leaderboard, name='leaderboard'),
    url(r'^q/(?P<slug>[-\w]+)/$', combat_views.QuizView.as_view(), name='quiz'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/signup/$', auth_views.signup, name='signup'),
    url(r'^accounts/profile/(?P<slug>[-\w]+)/$', auth_views.ProfileView.as_view(), name='profile_view'),
    url(r'^accounts/update/(?P<slug>[-\w]+)/$', auth_views.ProfileUpdate.as_view(), name='profile_update'),
    url(r'^accounts/password/(?P<pk>\d+)/$', auth_views.PasswordChangeView.as_view(), name='change_password'),


]

web/urls.py
from django.conf.urls import url
from django.contrib import admin
from combat import views as combat_views
from auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', auth_views.home, name='home'),
    url(r'^challenges/$', combat_views.challenges, name='challenges'),
    url(r'^leaderboard/$', combat_views.leaderboard, name='leaderboard'),
    url(r'^profile/(?P<slug>[-\w]+)/$', auth_views.ProfileView.as_view(), name='profile'),
    url(r'^q/(?P<slug>[-\w]+)/$', combat_views.QuizView.as_view(), name='quiz'),
    url(r'^evaluate/$', combat_views.evaluate, name='evaluate'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/signup/$', auth_views.signup, name='signup'),

]

combat/models.py
import os
import uuid
import datetime
from django.conf import settings as conf_settings
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
@receiver(post_save, sender=User)
def update_user_contestant(sender, instance, created, **kwargs):
    if created:
        Contestant.objects.create(user=instance)
    instance.contestant.save()


def uuid4hex():
    return uuid.uuid4().hex


class Contestant(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=63, unique=True)
    nickname = models.CharField(max_length=31, null=True, blank=True)
    sparko = models.IntegerField(default=0)
    github = models.URLField(null=True, blank=True)
    linkedin = models.URLField(null=True, blank=True)
    facebook = models.URLField(null=True, blank=True)
    last_update = models.DateTimeField(default=timezone.now)
    created = models.BooleanField(default=False)
    submits = models.IntegerField(default=0)
    elapsed = models.DurationField(default=datetime.timedelta, blank=True, null=True)

    class Meta:
        verbose_name = "Contestant"
        verbose_name_plural = "Contestant"

    def __str__(self):
        if self.nickname:
            return '{}'.format(self.nickname)
        else:
            return '{}'.format(self.user.username)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username.replace('.', '-'))
        if not self.nickname:
            self.nickname = self.user.username
        super(Contestant, self).save(*args, **kwargs)

    def valid_name(self):
        return 'user_{}'.format(self.uid.hex)

    def get_absolute_url(self):
        return reverse('profile_view', kwargs={'slug': self.slug})


def quiz_directory_path(instance, filename):
        subname = 'quiz/{0}/{1}'.format(instance.slug, filename)
        fullname = os.path.join(conf_settings.MEDIA_ROOT, subname)
        if os.path.exists(fullname):
            os.remove(fullname)
        return subname


class Quiz(models.Model):
    DIFFICULT_CHOICES = (
        ('tutorial', 'tutorial'),
        ('easy', 'easy'),
        ('medium', 'medium'),
        ('hard', 'hard')
    )

    STATUS_CHOICES = (
        ('draft', 'draft'),
        ('published', 'published')
    )
    uid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    title = models.CharField(max_length=1023, unique=True)
    slug = models.SlugField(max_length=1023, unique=True)
    dirname = models.CharField(max_length=1023)
    description = models.FileField(upload_to=quiz_directory_path, null=True, blank=True)
    prerequisite_py = models.TextField(blank=True, null=True)
    template_py = models.FileField(upload_to=quiz_directory_path, null=True, blank=True)
    prerequisite_scala = models.TextField(blank=True, null=True)
    template_scala = models.FileField(upload_to=quiz_directory_path, null=True, blank=True)
    reward = models.IntegerField(default=0)
    submits = models.IntegerField(default=0)
    passes = models.IntegerField(default=0)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    difficulty = models.CharField(
        max_length=15,
        choices=DIFFICULT_CHOICES,
        default='tutorial',
        null=True, blank=True
    )
    status = models.CharField(
        max_length=15,
        default='draft',
        choices=STATUS_CHOICES
    )

    class Meta:
        verbose_name = "Quiz"
        verbose_name_plural = "Quiz"

    def __str__(self):
        max_length = 3
        short_name = self.title.split()[:max_length]
        if len(short_name) < max_length:
            return '[{}] {}'.format(self.difficulty, self.title)
        else:
            return '[{}] {} ...'.format(self.difficulty, ' '.join(short_name))

    def get_absolute_url(self):
        return reverse('quiz', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Quiz, self).save(*args, **kwargs)

    def valid_name(self):
        return 'quiz_{}'.format(self.uid.hex)


def snippet_directory_path(instance, filename):
    subname = 'snippet/{0}/{1}/{2}'.format(
        instance.contestant.valid_name(), instance.quiz.valid_name(), instance.valid_name()
    )
    fullname = os.path.join(conf_settings.MEDIA_ROOT, subname)
    if os.path.exists(fullname):
        os.remove(fullname)
    return subname


class Snippet(models.Model):

    LANGUAGE_CHOICES = (
        ('python3', 'python3'),
        ('scala', 'scala')
    )

    STATUS_CHOICES = (
        ('unknown', 'unknown'),
        ('fail', 'fail'),
        ('pass', 'pass'),
        ('compile', 'compilation error'),
        ('runtime', 'runtime error'),
        ('memory', 'memory exceeded'),
        ('running', 'running')
    )

    uid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    language = models.CharField(
        max_length=15,
        choices=LANGUAGE_CHOICES,
        default='python3'
    )
    body = models.TextField()

    script = models.FileField(upload_to=snippet_directory_path)

    created = models.DateTimeField(auto_now_add=True)
    last_run = models.DateTimeField(auto_now=True)
    run_count = models.IntegerField(default=0)
    run_result = models.TextField(null=True, blank=True)

    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        null=True, blank=True
    )

    is_running = models.BooleanField(default=False)
    # is_pass = models.BooleanField(default=False)

    submit = models.BooleanField(default=False)
    submit_time = models.DateTimeField(null=True, blank=True)

    contestant = models.ForeignKey(
        'Contestant',
        models.SET_NULL,
        null=True, blank=True
    )

    quiz = models.ForeignKey(
        'Quiz',
        models.SET_NULL,
        null=True, blank=True
    )

    class Meta:
        verbose_name = "Snippet"
        verbose_name_plural = "Snippet"
        unique_together = ('contestant', 'quiz', 'language')

    def valid_name(self):
        return 'script_{}'.format(self.uid.hex)

    def __str__(self):
        return '{} @ {}'.format(self.quiz, self.contestant)


def answer_directory_path(instance, filename):
    subname = 'answer/{0}/{1}/{2}'.format(
        instance.contestant.valid_name(), instance.quiz.valid_name(), instance.valid_name()
    )
    fullname = os.path.join(conf_settings.MEDIA_ROOT, subname)
    if os.path.exists(fullname):
        os.remove(fullname)
    return subname


class Answer(models.Model):
    LANGUAGE_CHOICES = (
        ('python3', 'python3'),
        ('scala', 'scala')
    )

    uid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    language = models.CharField(
        max_length=15,
        choices=LANGUAGE_CHOICES,
        default='python3'
    )

    contestant = models.ForeignKey(
        'Contestant', models.SET_NULL,
        null=True, blank=True
    )

    quiz = models.ForeignKey(
        'Quiz', models.SET_NULL,
        null=True, blank=True
    )

    body = models.TextField()
    script = models.FileField(upload_to=answer_directory_path)

    created = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)
    submits = models.IntegerField(default=0)
    elapsed = models.DurationField(blank=True, null=True)

    class Meta:
        verbose_name = "Answer"
        verbose_name_plural = "Answer"
        unique_together = ('contestant', 'quiz', 'language')

    def valid_name(self):
        return 'answer_{}'.format(self.uid.hex)

combat/forms.py
from django import forms
from combat.models import Snippet
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.forms.widgets import Select
from django.utils import timezone
# from django.forms.widgets import TextInput


class SnippetForm(forms.ModelForm):
    class Meta:
        model = Snippet
        exclude = ['script', 'run_count']

    def save(self, commit=True):
        instance = super(SnippetForm, self).save(commit=False)

        if self.cleaned_data.get('body', '') != self.initial.get('body', ''):
            path = 'snippet/{0}/{1}/{2}.{3}'.format(
                instance.contestant.valid_name(),
                instance.quiz.valid_name(),
                instance.valid_name(),
                'scala' if 'scala' in instance.language else 'py'
            )
            default_storage.delete(path)
            instance.script = default_storage.save(path, ContentFile(instance.body))
            instance.run_count += 1
        instance.is_running = True
        instance.last_run = timezone.now()
        if commit:
            instance.save()

        return instance


class LanguageForm(forms.ModelForm):
    class Meta:
        model = Snippet
        fields = ('language',)
        widgets = {
            'language': Select(attrs={'class': 'selectpicker', 'data-width': '120px'}),
        }

combat/views.py
import logging
import json
from django.core.files.storage import default_storage
from django.conf import settings as django_settings
from django.shortcuts import render
from django.forms.models import model_to_dict
import requests
from django.utils import timezone
from django.http import HttpResponse
from django.views.generic import DetailView
from django.core.serializers.json import DjangoJSONEncoder

from rest_framework.renderers import JSONRenderer

from combat.models import Quiz, Snippet, Contestant, Answer
from combat.forms import LanguageForm
from combat.utils import QuizData, SnippetData, MyDict

from configparser import RawConfigParser
config_parser = RawConfigParser()
configfile = config_parser.read('sparktw.config.ini')
if bool(configfile):
    spark_backend_host = config_parser.get('global', 'spark_backend_host')
else:
    spark_backend_host = 'localhost:3000'
# Create your views here.

logger = logging.getLogger('combat')


class JSONResponse(HttpResponse):
    """An HttpResponse that renders its content into JSON."""

    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs['content_type'] = 'application/json'
        super(JSONResponse, self).__init__(content, **kwargs)


def challenges(request):
    quizs = Quiz.objects.all()
    if not request.user.is_staff:
        quizs = quizs.filter(status='published')
    return render(request, 'challenges.html', {'quizs': quizs})


def leaderboard(request):
    contestants = Contestant.objects \
        .order_by('-sparko', 'last_update', 'submits', 'elapsed')

    if not request.user.is_staff:
        contestants = contestants.filter(user__is_staff=False)
    return render(request, 'ranking.html', {'contestants': contestants})


class QuizView(DetailView):
    template_name = 'quiz.html'
    model = Quiz
    context_object_name = 'quiz'
    create_user_url = 'http://{}/create/user'.format(spark_backend_host)

    def get_context_data(self, **kwargs):
        context = super(QuizView, self).get_context_data(**kwargs)

        description = (
            default_storage.open(self.object.description.path).read().decode('utf-8')
            if self.object.description else '### No description.'
        )

        qdata = QuizData(
            description=description,
            title=self.object.title,
            uid=self.object.uid.hex,
            status=self.object.status,
            difficulty=self.object.difficulty or 'tutorial',
            reward=self.object.reward
        )

        snippets = MyDict()
        current = None

        templates = [
            ('python3', self.object.template_py),
            ('scala', self.object.template_scala)
        ]

        if self.request.user.is_authenticated():
            if not (django_settings.DEBUG or self.request.user.contestant.created):

                # TODO: this api should be issued by backend workers, ex: Celery.
                r = requests.post(
                    self.create_user_url,
                    json.dumps(
                        dict(user=self.request.user.contestant.valid_name())
                    ),
                    timeout=5
                )
                rdata = json.loads(r.content.decode('utf-8'))
                if rdata['response_code'] == 0:
                    self.request.user.contestant.created = True
                    self.request.user.contestant.save()

            answers = Answer.objects.filter(
                contestant=self.request.user.contestant,
                quiz=self.object
            )
            snips = Snippet.objects.filter(
                contestant=self.request.user.contestant,
                quiz=self.object
            ).order_by('-last_run')

            if bool(snips):
                for s in snips:
                    is_pass = answers.filter(language=s.language).exists()
                    elapsed = (timezone.now() - s.created).total_seconds()
                    snippets[s.language] = SnippetData(
                        language=s.language,
                        body=s.body,
                        uid=s.uid.hex,
                        run_count=s.run_count,
                        contestant_id=s.contestant.id,
                        quiz_id=self.object.id,
                        status=s.status,
                        is_submit=True,
                        is_running=s.is_running,
                        is_pass=is_pass,
                        elapsed=answers.get(language=s.language).elapsed.total_seconds() if is_pass else elapsed,
                        created=s.created.timestamp()
                    )
                    if not bool(current):
                        current = snippets[s.language]

        for lang, file in templates:
            if lang not in snippets:
                body = (
                    default_storage.open(file.path).read().decode('utf-8')
                    if bool(file) else '# Write your answer below.\n\n'
                )
                snippets[lang] = SnippetData(
                    language=lang,
                    body=body,
                    quiz_id=self.object.id,
                    contestant_id=self.request.user.contestant.id if self.request.user.is_authenticated() else -1,
                    created=timezone.now().timestamp()
                )

        if not bool(current):
            current = snippets['python3']

        context['form'] = LanguageForm(initial={'language': current.get('language', 'python3')})
        context['quizdata'] = qdata
        context['current'] = current
        context['snippetdata'] = snippets

        return context

combat/templates/challenges.html
{% extends "index.html" %}
{% load combat_tags %}

{% block main-content %}

{% if quizs %}

<div class="row">
    <div class="col-md-8 col-md-offset-0">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                  <th>Difficulty</th>
                  <th>Title</th>
                  <th>Reward</th>
                  <th>Submits</th>
                  <th>Passed</th>
                </tr>
            </thead>
            <tbody>
                {% for q in quizs %}
                    <tr>
                        <td scope="row"><span class="label 
                        {% if q.difficulty == 'tutorial' %}
                            label-primary
                        {% elif q.difficulty == 'easy' %}
                            label-success
                        {% elif q.difficulty == 'medium' %}
                            label-warning
                        {% elif q.difficulty == 'hard' %}
                            label-danger
                        {% else %}
                            label-default
                        {% endif %} label-as-badge">{{ q.difficulty|pretty_title }}</span></td>
                        <td>
                            <a id="quiz" href="{% url "quiz" slug=q.slug %}">{{ q.title|pretty_title }}</a>
                            {% if q.status == "draft" %}
                                <span class="label label-info label-as-badge" style="margin-left: 10px;">{{ q.status }}</span>
                            {% endif %}
                        </td>
                        <td><span class="label label-info label-as-badge">{{ q.reward }}</span></td>
                        <td>{{ q.submits }}</td>
                        <td>{{ q.passes }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% else %}
    <h2>There is no challenges.</h2>
{% endif %}
{% endblock main-content %}


{% block extend-js %}

{% endblock %}

combat/templates/quiz.html
{% extends "index.html" %}

{% load i18n admin_static %}
{% load combat_tags %}

{% block extend-style %}
<style>
#ace-editor {
    position: relative;
    width: 100%;
    height: 500px;
    font-size: 16px;
}
</style>
{% endblock extend-style %}

{% block main-content %}



<div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="callout callout-orange">
                <span class="label 
                            {% if quizdata.difficulty == 'tutorial' %}
                                label-primary
                            {% elif quizdata.difficulty == 'easy' %}
                                label-success
                            {% elif quizdata.difficulty == 'medium' %}
                                label-warning
                            {% elif quizdata.difficulty == 'hard' %}
                                label-danger
                            {% else %}
                                label-default
                            {% endif %} label-as-badge">
                            {{ quizdata.difficulty|pretty_title }}
                </span>
                &nbsp;
                <span class="label label-purple label-as-badge">
                    <span class="glyphicon glyphicon-star"></span>
                    {{ quizdata.reward }}
                </span>
                &nbsp;
                <span id="elapsed_timer" class="label label-default label-as-badge"></span>
                
                <h1><span id="id_ispass" class="label label-success"></span>&nbsp;{{ quizdata.title|pretty_title }}</h1>
            </div>

            <div class="tabbable">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#markdown-preview" data-toggle="tab">Description</a>
                    </li>
                    <li>
                        <a href="#evaluate-console" data-toggle="tab">Console<img src="{% static "img/loading.gif" %}" width="30px;" id="loading_icon" style="display: none;"></a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="markdown-preview" style="padding: 20px; background-color: #fefaee;"></div>
                    <div class="tab-pane console" id="evaluate-console">
                    </div>
                </div>
            </div>
            <div class="row" style="margin: 20px 0 5px;">
            
                {{ form.language }}
                
                <select class="selectpicker" id="themepicker" data-width="150px">
                    <option>twilight</option>
                    <option>solarized_light</option>
                    <option>solarized_dark</option>
                </select>

                {% if user.is_authenticated %}
                    <button id="btn_evaluate" class="btn btn-primary pull-right">執行</button>
                {% else %}
                    <a href="{% url "signup" %}?next={{ request.path }}"><button class="btn btn-primary pull-right">執行</button></a>
                {% endif %}
            </div>
            
            <div type="text" name="body" type="text" name="body" id="ace-editor"></div>

        </div>
</div>

{% endblock main-content %}

{% block extend-js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.7/ace.js"></script>
    <script type="text/javascript" src="{% static "channels/js/websocketbridge.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datejs/1.0/date.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/languages/scala.min.js"></script>

    <script>hljs.initHighlightingOnLoad();</script>

    <script type="text/javascript">

        var md = window.markdownit();
        var quizdata = JSON.parse("{{ quizdata|escapejs }}");
        console.log("{{ quizdata|escapejs }}");
        var snippetdata = JSON.parse("{{ snippetdata|escapejs }}");
        var currdata = JSON.parse("{{ current|escapejs }}");

        var $editor = ace.edit("ace-editor");
        var $evaluate_console = $("#evaluate-console");
        var $markdown_preview = $("#markdown-preview");
        var $themepicker = $("#themepicker");
        var $languagepicker = $("#id_language");
        var $loading_icon = $("#loading_icon");
        var $btn_evaluate = $('#btn_evaluate');
        var $elapsed_timer = $('#elapsed_timer');

        var update_elapsed = function() {
            var lang = $languagepicker.val();
            var $pass_block = $('#id_ispass');
            $elapsed_timer.empty();
            $pass_block.empty();
            if(snippetdata[lang].is_submit) {
                if(snippetdata[lang].is_pass) {
                    $elapsed_timer.text(format_elapsed(snippetdata[lang].elapsed));
                    $('#id_ispass').html('pass');
                } else {
                    $elapsed_timer.text(format_elapsed($.now()/1000 - snippetdata[lang].created));
                }
            }
        }
        update_elapsed();
        

        

        $markdown_preview.html(md.render(quizdata.description));

        if(currdata.is_running) {
            $loading_icon.show();
            $btn_evaluate.prop('disabled', true);
            $('.nav-tabs a[href="#evaluate-console"]').tab('show');
        }

        $themepicker.on("change", function(evt) {
            $editor.setTheme( "ace/theme/" + $(this).val());
        });
        $themepicker.val(localStorage[quizdata.uid + "-theme"] || "twilight");

        $languagepicker.on("change", function(evt) {
            $editor.session.setMode("ace/mode/" + $(this).val().replace(/\d|\./g, ''));
            $editor.setValue(snippetdata[$(this).val()].body);
            update_elapsed();
        })
        setInterval(update_elapsed, 1000);
        
        $editor.setTheme( "ace/theme/" + $themepicker.val());
        $editor.session.setMode("ace/mode/" + $languagepicker.val().replace(/\d|\./g, ''));
        $editor.$blockScrolling = Infinity;
        $editor.setValue(currdata.body);

        // Locally autosave
        // $editor.getSession().on('change', function(e) {
        //     data = $editor.getValue();
        // });

        if (currdata.contestant_id >= 0) {
            const webSocketBridge = new channels.WebSocketBridge();
            webSocketBridge.connect('/evaluate/');
    
            webSocketBridge.listen(function(action, stream) {
                var code = action.response_code,
                    date = new Date(action.timestamp * 1000);
                    message = action.response_message;
                var element = document.createElement('div'),
                    node = document.createTextNode(date.toString('[MM/dd h:mm:ss] ') + message),
                    color = ['chartreuse ', 'orange', 'hotpink'];

                if(code >= 0) {
                    element.style.color = color[code];
                } else if (code == -1) {
                    snippetdata[$languagepicker.val()].is_pass = true;
                    snippetdata[$languagepicker.val()].elapsed = $.now()/1000 - snippetdata[$languagepicker.val()].created;
                }
                element.appendChild(node);
                $evaluate_console.append(element);
                $evaluate_console.scrollTop($evaluate_console[0].scrollHeight);
                if (code == -10) {
                    $loading_icon.hide();
                    $btn_evaluate.prop('disabled', false);
                }
            });
    
            $btn_evaluate.on('click', function(){
                $(this).prop('disabled', true);
                $loading_icon.show();
                if (!snippetdata[$languagepicker.val()].is_submit) {
                    snippetdata[$languagepicker.val()].is_submit = true;
                    snippetdata[$languagepicker.val()].created = $.now() / 1000;
                }
                // Show console tab and wait for result messages.
                $('.nav-tabs a[href="#evaluate-console"]').tab('show');
                webSocketBridge.send({
                    'language': $languagepicker.val(),
                    'body': $editor.getValue(),
                    'contestant': currdata.contestant_id,
                    'quiz': currdata.quiz_id
                });
            });
	}

        $(window).unload(function() {
            localStorage[quizdata.uid + "-theme"] = $themepicker.val();
        });

    </script>
{% endblock %}

combat/templates/ranking.html
{% extends "index.html" %}
{% load combat_tags %}
{% block main-content %}

{% if contestants %}

<div class="row">
    <div class="col-md-8 col-md-offset-0">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                  <th>#Ranking</th>
                  <th>Name</th>
                  <th>Score</th>
                  <th>Last Update (UTC+8)</th>
                  <th>Submits</th>
                  <th>Elapsed</th>
                </tr>
            </thead>
            <tbody>
                {% for cont in contestants %}
                    <tr>
                        <td scope="row">
                            <span class="label {% if forloop.first %} label-danger {% else %} label-primary {% endif %} label-as-badge">{{ forloop.counter }}</span>
                        </td>
                        <td>
                            <a href="{% url "profile_view" slug=cont.slug %}">{{ cont.nickname }}</a>
                            {% if cont.user.is_staff %}
                                <span class="label label-info label-as-badge" style="margin-left: 10px;">staff</span>
                            {% endif %}
                        </td>
                        <td><span class="label label-success label-as-badge">{{ cont.sparko }}</span></td>
                        <td> {{ cont.last_update }} </td>
                        <td> {{ cont.submits }} </td>
                        <td><span class="label label-default label-as-badge"> {{ cont.elapsed|pretty_duration }}</span></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
 
{% else %}
    <h2>There is no contestants.</h2>
{% endif %}
{% endblock main-content %}


{% block extend-js %}

{% endblock %}